name: Task
description: Track a development task
title: "[Task] "
labels: ["status/todo"]
body:
  - type: textarea
    attributes:
      label: Goal
      description: What outcome do we want?
    validations:
      required: true

  - type: textarea
    attributes:
      label: Context
      description: Background, links, constraints

  - type: textarea
    attributes:
      label: Scope
      description: What is included / excluded

  - type: textarea
    attributes:
      label: Acceptance Criteria
      description: Definition of done
    validations:
      required: true

  - type: textarea
    attributes:
      label: Verify / Test Commands

  - type: textarea
    attributes:
      label: Notes / Logs
