// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/yanqian/ai-helloworld/internal/bootstrap"
	"github.com/yanqian/ai-helloworld/internal/domain/auth"
	"github.com/yanqian/ai-helloworld/internal/domain/faq"
	"github.com/yanqian/ai-helloworld/internal/domain/summarizer"
	"github.com/yanqian/ai-helloworld/internal/domain/uvadvisor"
	"github.com/yanqian/ai-helloworld/internal/infra/config"
	"github.com/yanqian/ai-helloworld/internal/interface/http"
	"github.com/yanqian/ai-helloworld/pkg/logger"
)

// Injectors from wire.go:

func initializeApp() (*bootstrap.App, error) {
	configConfig, err := config.Load()
	if err != nil {
		return nil, err
	}
	// summarizer dependencies
	slogLogger := logger.New()
	summarizerConfig := provideSummaryConfig(configConfig)
	client, err := provideChatGPTClient(configConfig)
	if err != nil {
		return nil, err
	}
	service := summarizer.NewService(summarizerConfig, client, slogLogger)
	// uvadvisor dependencies
	uvadvisorConfig := provideUVAdvisorConfig(configConfig)
	datagovClient := provideUVClient(configConfig)
	uvadvisorService := uvadvisor.NewService(uvadvisorConfig, datagovClient, client, slogLogger)
	// faq dependencies
	faqConfig := provideFAQConfig(configConfig)
	questionRepository := provideFAQRepository(configConfig, slogLogger)
	store := provideFAQStore(configConfig, slogLogger)
	faqService := faq.NewService(faqConfig, questionRepository, store, client, slogLogger)
	// upload ask dependencies
	uploadAskConfig := provideUploadAskConfig(configConfig)
	objectStorage := provideUploadStorage(configConfig, slogLogger)
	uploadEmbedder := provideUploadEmbedder(client, configConfig, slogLogger)
	chunker := provideUploadChunker()
	uploadDocumentRepository := provideUploadDocumentRepository(configConfig, slogLogger)
	uploadFileRepository := provideUploadFileRepository(configConfig, slogLogger)
	uploadChunkRepository := provideUploadChunkRepository(configConfig, uploadDocumentRepository, slogLogger)
	uploadQASessionRepository := provideUploadSessionRepository(configConfig, slogLogger)
	uploadQueryLogRepository := provideUploadQueryLogRepository(configConfig, slogLogger)
	uploadQueue := provideUploadQueue(configConfig, slogLogger)
	uploadLLM := provideUploadLLM(client, configConfig, slogLogger)
	uploadService := provideUploadService(uploadAskConfig, uploadDocumentRepository, uploadFileRepository, uploadChunkRepository, uploadQASessionRepository, uploadQueryLogRepository, objectStorage, uploadEmbedder, uploadLLM, chunker, uploadQueue, slogLogger)
	authConfig := provideAuthConfig(configConfig)
	repository := provideAuthRepository(configConfig, slogLogger)
	authService := auth.NewService(authConfig, repository, slogLogger)
	handler := http.NewHandler(service, uvadvisorService, faqService, authService, uploadService, slogLogger)
	server := http.NewRouter(configConfig, handler)
	app := bootstrap.NewApp(configConfig, slogLogger, server)
	return app, nil
}
