// Code generated by Wire; DO NOT EDIT.

//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/yanqian/ai-helloworld/internal/bootstrap"
	"github.com/yanqian/ai-helloworld/internal/domain/faq"
	"github.com/yanqian/ai-helloworld/internal/domain/summarizer"
	"github.com/yanqian/ai-helloworld/internal/domain/uvadvisor"
	"github.com/yanqian/ai-helloworld/internal/infra/config"
	httpiface "github.com/yanqian/ai-helloworld/internal/interface/http"
	"github.com/yanqian/ai-helloworld/pkg/logger"
)

func initializeApp() (*bootstrap.App, error) {
	configConfig, err := config.Load()
	if err != nil {
		return nil, err
	}
	summarizerConfig := provideSummaryConfig(configConfig)
	uvadvisorConfig := provideUVAdvisorConfig(configConfig)
	faqConfig := provideFAQConfig(configConfig)
	slogLogger := logger.New()
	chatgptClient, err := provideChatGPTClient(configConfig)
	if err != nil {
		return nil, err
	}
	client := provideUVClient(configConfig)
	repository := provideFAQRepository(configConfig, slogLogger)
	store := provideFAQStore(configConfig, slogLogger)
	service := summarizer.NewService(summarizerConfig, chatgptClient, slogLogger)
	service2 := uvadvisor.NewService(uvadvisorConfig, client, chatgptClient, slogLogger)
	service3 := faq.NewService(faqConfig, repository, store, chatgptClient, slogLogger)
	handler := httpiface.NewHandler(service, service2, service3, slogLogger)
	httpServer := httpiface.NewRouter(configConfig, handler)
	app := bootstrap.NewApp(configConfig, slogLogger, httpServer)
	return app, nil
}
